Repository fga-eps-mds/2020.2-CheeryUP-FrontEnd, pull requests merged in 2021-04, with the labels that each got.

#14 Feature/PagCadastroPaciente #117
  src/components/Navbar/MenuItems.js
  src/components/Navbar/NavbarPsic.js
  src/pages/Registrar/CadastroPaciente.js
  src/routes.js
  src/style/pages/Cadastro/CadastroPaciente.css
  src/style/pages/HomePage/Navbar.css
Labels: front-end

#18 DevOPS_CD
  .github/workflows/CD.yml
Labels: devOps

#23 Implementacao grafico
  package-lock.json
  package.json
  src/components/Graficos/GraficoRegiao.js
  src/pages/DashboardPacientes/DashboardPacientes.js
  src/routes.js
Labels: bug, front-end

#22 Perfil psicologo
  public/img/imgPerfilPsicologo.png
  src/components/Navbar/MenuItems.js
  src/components/Navbar/NavbarPsic.js
  src/pages/PerfilPsicologo/PerfilPsicologo.js
  src/routes.js
  src/style/pages/HomePage/NavbarAlt.css
  src/style/pages/HomePage/NavbarPsic.css
  src/style/pages/PerfilPsicologo/PerfilPsicologo.css
Labels: front-end
